# Generated by Django 5.1.1 on 2024-11-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_uz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='view',
            field=models.IntegerField(null=0),
        ),
    ]
